export const SITE_STATUSES = [
  "开放参观",
  "预约参观",
  "外观可见",
  "暂不开放",
  "状态未知",
] as const;

export type SiteStatus = (typeof SITE_STATUSES)[number];

export const SITE_CATEGORIES = [
  "钢铁工业",
  "电子工业",
  "纺织工业",
  "电力工业",
  "船舶工业",
  "铁路工业",
  "铁路交通",
  "食品工业",
  "机械制造",
  "罐头食品工业",
  "印刷工业",
  "其他工业",
  "有色金属",
  "核工业",
  "煤炭工业",
  "化工工业",
  "建材工业",
  "造纸印刷",
  "军工国防",
  "航空航天",
] as const;

export type SiteCategory = (typeof SITE_CATEGORIES)[number];
export type SiteSource = string;

export interface SiteImage {
  url: string;
  alt?: string;
  source?: SiteSource;
}

export interface SiteRecord {
  id: string;
  name: string;
  province: string;
  provinceFull: string;
  city: string;
  primaryCity: string;
  cityList: string[];
  district?: string;
  districtList: string[];
  lat: number;
  lng: number;
  category: SiteCategory;
  status: SiteStatus;
  featured: boolean;
  featuredOrder: number;
  level?: string;
  batch?: string;
  era?: string;
  description?: string;
  historicalBackground?: string;
  researchValue?: string;
  address?: string;
  source?: SiteSource;
  images?: SiteImage[];
  visitAccess?: string;
  currentUse?: string;
  visibleRemains?: string;
  riskNote?: string;
  searchText: string;
}

export interface LegacySiteRecord {
  id: string;
  name: string;
  city: string;
  district?: string;
  type: string;
  status: SiteStatus;
  year?: number;
  lat: number;
  lng: number;
  coverImage?: string;
  summary?: string;
  historicalBackground?: string;
  researchValue?: string;
  address?: string;
  visitAccess?: string;
  currentUse?: string;
  visibleRemains?: string;
  riskNote?: string;
}

export type RawSiteRecord = Partial<SiteRecord> & Partial<LegacySiteRecord>;

export const SITE_FILTER_KEYS = ["province", "city", "category", "status", "level", "batch", "keyword"] as const;

export type SiteFilterKey = (typeof SITE_FILTER_KEYS)[number];
export type LinkedSiteFilterKey = Exclude<SiteFilterKey, "keyword">;

export interface SiteFilters {
  province: string;
  city: string;
  category: string;
  status: string;
  level: string;
  batch: string;
  keyword: string;
}

export interface SiteFilterOption {
  value: string;
  count: number;
  disabled: boolean;
}

export interface SiteFilterOptions {
  provinces: SiteFilterOption[];
  cities: SiteFilterOption[];
  categories: SiteFilterOption[];
  statuses: SiteFilterOption[];
  levels: SiteFilterOption[];
  batches: SiteFilterOption[];
}

export interface SiteRegionStat {
  value: string;
  count: number;
}

export interface SiteFacetCounts {
  provinces: Record<string, number>;
  cities: Record<string, number>;
  categories: Record<string, number>;
  statuses: Record<string, number>;
  levels: Record<string, number>;
  batches: Record<string, number>;
}

export interface ExplorationRouteStop {
  order: number;
  site: Site;
}

export interface ExplorationRoute {
  stops: ExplorationRouteStop[];
  siteIds: string[];
  coordinates: [number, number][];
  /** True when this route was generated by the AI explore feature. */
  isAiRoute?: boolean;
}

export type SiteMapRelationLevel =
  | "default"
  | "selected"
  | "same-city"
  | "same-province"
  | "same-category"
  | "dimmed";

export interface SiteMapMarkerState {
  relationLevel: SiteMapRelationLevel;
  isSelected: boolean;
  isHovered: boolean;
  isInRoute: boolean;
  isRouteStart: boolean;
  isRouteEnd: boolean;
  isDimmedByRoute: boolean;
}

export interface SiteMapBounds {
  north: number;
  south: number;
  east: number;
  west: number;
}

export type Site = SiteRecord;
